### ISSUE TITLE
FileNotFoundError on a fresh copy of Raspbian

### ISSUE THREAD

**Issue by rGunti** [pimoroni/keybow-python#3]
Downloaded a fresh copy of Raspbian and cloned the code for the samples.

Setup the Pi using the following commands:
```
sudo apt install -y git python3 python3-pip python-rpi.gpio python3-rpi.gpio
sudo pip3 install --upgrade pip
sudo pip3 install spidev
sudo pip3 install keybow
```

Then tried to execute the sample `minikeyleds.py` but got the following Traceback:
```
Traceback (most recent call last):
  File "leds.py", line 16, in <module>
    keybow.set_pixel(x, r, g, b)
  File "/usr/local/lib/python3.7/dist-packages/keybow/__init__.py", line 65, in set_led
    setup()
  File "/usr/local/lib/python3.7/dist-packages/keybow/__init__.py", line 52, in setup
    spi.open(0, 0)
FileNotFoundError: [Errno 2] No such file or directory
```

What did I forget? And if so, the README should probably reflect that.

**Comment by Gadgetoid** [comment]
Looks like it's missing the step to enable SPI. And, indeed, the README doesn't mention this.

An easy one-liner for that is: `sudo raspi-config nonint do_spi 0`
