### ISSUE TITLE
Lua: Unable to break out of while loop once key is pressed

### ISSUE THREAD

**Issue by DanAtkinson** [pimoroni/keybow-python#7]
Apologies if this is better asked on somewhere like Stackoverflow but I think that my question is relating to the nature of the `keybow_sleep` function and whether there are better (non-blocking) alternatives that I should be using instead for my particular scenario.

I have the below function which executes when key 7 is pressed (third row up, middle key).

My requirement is that, once key 7 is pressed, turn the key light on and press the left ctrl key every second until key 7 is pressed again. At which point, the next loop should break.

```lua

key07Pressed = false
function handle_key_07(pressed)

  if pressed then
    -- Reverse the key07Pressed Boolean value.
    key07Pressed = not(key07Pressed)
    -- Only execute if the key07Pressed Bool is true.
    if key07Pressed then
      -- Turn the key light on (white).
      keybow.set_pixel(7, 255, 0, 255)
      while key07Pressed
      do
        -- Change the key colour to cyan to let the user know we're executing the loop.
        keybow.set_pixel(7, 0, 255, 255)
        -- Tap the left control key. It's probably unnecessary to do the down and up, and I could probably just get away with doing tap_key(keybow.LEFT_CTRL).
        keybow.set_modifier(keybow.LEFT_CTRL, keybow.KEY_DOWN)
        keybow.sleep(100)
        keybow.set_modifier(keybow.LEFT_CTRL, keybow.KEY_UP)

        -- Change the key colour back to white.
        keybow.set_pixel(7, 255, 255, 255)

        -- Sleep for 1 second.
        keybow.sleep(1000)
      end
      -- If we're here, then the loop has been broken. In which case, turn the key light to black (off).
      keybow.set_pixel(7, 0, 0, 0)
    end
  end
end
```

What happens is that, once key 7 is pressed, the logic enters the while loop and does not leave. This seems to be because the `keybow_sleep` function appears to be blocking and therefore other keys do not work. The consequence is that, if I then press key 7 again (which should set the `key07Pressed` value back to `false`) it does nothing because the keypress is not registered.

Is there a better method of achieving my requirement? Have I coded something wrong here? This is the first time I've coded in Lua so I'm a little unsure of best practices around loops and sleeping but it appears to be single-threaded and blocking.

**Comment by Gadgetoid** [comment]
I think this probably relates to https://github.com/pimoroni/keybow-firmware/ rather than the Python code, but no matter!

Keybow's Lua bindings have a main loop (`function tick()`) that you can use, probably the best example of this for your purposes might be the new mouse example: https://github.com/pimoroni/keybow-firmware/blob/master/sdcard/layouts/mouse.lua

All of the contents in `tick()` are run- in theory- every 1000us (0.001s).

You should avoid the use of `keybow.sleep()` altogether, since it will block keyboard input.

Instead you should use `keybow_get_millis()` (which doesn't appear to have a `keybow.get_millis()` counterpart yet) to make a note of the time you transition `LEFT_CTRL`, and change it for every 100 millis.

You could probably use `math.floor((keybow_get_millis() / 100) % 2)` to generate a variable that alternates between 0 and 1 every 100ms, and then just plug that right into `keybow.set_modifier`.

**Comment by DanAtkinson** [comment]
Hi @Gadgetoid,

Thank you for the reply. My apologies for posting in the wrong place. I didn't realise there was a different repo but feel free to move it to there if needed.

I was using `keybow.sleep()` as that's what all of the code samples use but I don't see how I can use `tick()` in the same way. Once the key is pressed, I need to wait 1 second but it's unclear how this would work.

I assume I can just wire in `keybow.get_millis` with the below addition to `keybow.lua`:
```lua
function keybow.get_millis()
    return keybow_get_millis()
end
```

If I then do something like the below...:

```lua
function tick()
  if key07Pressed and math.floor((keybow_get_millis() / 1000) % 2) then
    keybow.set_pixel(7, 0, 255, 255)
    keybow.set_key(keybow.LEFT_CTRL, true)
    keybow.set_key(keybow.LEFT_CTRL, false)
    keybow.set_pixel(7, 255, 255, 255)
  end
end

-- Third row up middle
key07Pressed = false
function handle_key_07(pressed)
  if not(pressed) then
    key07Pressed = not(key07Pressed)
    if not(key07Pressed) then
      keybow.set_pixel(7, 0, 0, 0) -- Black (off)
    end
end
```

How do I change it to only press the ctrl key once every second rather than once every tick? I had hoped that adding the mod check on the if statement was sufficient to alternate it to once every second but now the key just flashes wildly. :)

**Comment by Gadgetoid** [comment]
IIRC you *must* wait at least one "tick" for the key change to propagate via USB, too, so you can't do `set_key` to `true` and then `false` in quick succession.

One method of delaying 1s on keypress might be to store the time (`millis()`) when the key is pressed, and then check to see if the current time is greater than 1000 milliseconds.

In your case you might want something like (and forgive me for totally not testing, error or syntax checking this in any way):

```lua
function tick()
  if key07Pressed and keybow_get_millis() - key07time >= 1000 then
    toggle =  math.floor((keybow_get_millis() / 100) % 2)
    if toggle
        keybow.set_pixel(7, 0, 255, 255)
        keybow.set_key(keybow.LEFT_CTRL, true)
    else
       keybow.set_pixel(7, 255, 255, 255)
        keybow.set_key(keybow.LEFT_CTRL, false)
    end
  end
end

-- Third row up middle
key07Pressed = false
key07time = 0
function handle_key_07(pressed)
    key07time = keybow_get_millis()
    key07Pressed = pressed
    if not(key07Pressed) then
      keybow.set_pixel(7, 0, 0, 0) -- Black (off)
    end
end
```

**Comment by DanAtkinson** [comment]
Thank you.

I was using some examples of `set_key` in the `keybow.lua` file such as [`keybow.tap_shift`](https://github.com/pimoroni/keybow-firmware/blob/master/sdcard/keybow.lua#L234) which do the key down followed immediately by key up.

```lua
function keybow.tap_shift()
    keybow.set_key(keybow.LEFT_SHIFT, true)
    keybow.set_key(keybow.LEFT_SHIFT, false)
end
```

There are some problems with your code (although you did say that it was untested! 😄) in that it still attempted to set the key up or key down on every tick once the key had been pressed. Adding some debugging resulted in hundreds of lines of text being output every few seconds. However, once that I understand the problem, the `tick()` function, and `keybow_get_millis()`, I've come up with the below which works.

```lua
key07Time = 0
key07LastFireMod = 0
key07Pressed = false

function tick()
  -- If key07 is pressed and it's been more than 1000ms since the key was pressed...
  if key07Pressed and (keybow_get_millis() - key07Time) >= 1000 then
    -- If the key07LastFireMod is different to the current value, then change the value and perform the action.
    currentTickMod = math.floor((keybow_get_millis() / 1000) % 2)
    if currentTickMod ~= key07LastFireMod then
      key07LastFireMod = currentTickMod
      keybow.set_key(keybow.LEFT_CTRL, true)
      keybow.set_key(keybow.LEFT_CTRL, false)
    end
  end
end

-- Third row up middle
function handle_key_07(pressed)
  if not(pressed) then
    -- Execute when the key is lifted.
    key07Pressed = not(key07Pressed)
    key07Time = keybow_get_millis()

    if key07Pressed then
      keybow.set_pixel(7, 255, 255, 255) -- White
    else
      keybow.set_pixel(7, 0, 0, 0) -- Black (off)
    end
  end
end
```

Thank you very much for your help with this.
